package testbootstrap

import (
	"os"
	"path/filepath"
)

const cypressConfigTS = `// Generated by ASQS e2e_framework_bootstrap — safe to edit or delete.
import { defineConfig } from 'cypress';

export default defineConfig({
  e2e: {
    baseUrl: 'http://localhost:3000',
    specPattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}',
    supportFile: false,
  },
  video: false,
});
`

const cypressSmokeSpec = `// Minimal smoke spec so cypress run has something to execute.
describe('smoke', () => {
  it('placeholder', () => {
    expect(true).to.equal(true);
  });
});
`

func writeCypressConfig(dir string) error {
	p := filepath.Join(dir, "cypress.config.ts")
	if _, err := os.Stat(p); err == nil {
		return nil
	}
	return atomicWrite(p, []byte(cypressConfigTS))
}

func writeCypressSmokeSpec(dir string) error {
	e2eDir := filepath.Join(dir, "cypress", "e2e")
	if err := os.MkdirAll(e2eDir, 0755); err != nil {
		return err
	}
	p := filepath.Join(e2eDir, "smoke.cy.ts")
	if _, err := os.Stat(p); err == nil {
		return nil
	}
	return atomicWrite(p, []byte(cypressSmokeSpec))
}
