package testbootstrap

import (
	_ "embed"
	"os"
	"path/filepath"
	"strings"
)

// Route-control helpers for the Java and .NET Playwright bootstraps, mirroring what the JS/TS
// bootstrap writes to e2e/support/api.ts.
//
// The failure they answer is binding-independent. Run api-428e4bb1f792d71bacd54d8ba3953801
// intercepted correctly in TypeScript and then invented `route.delay(...)` to hold the response
// open; every Playwright binding offers interception, none offers a delay member on Route, and a
// model writing Java or .NET has the same reason to reach for one. Shipping the helper only for
// JS/TS would fix the language we happened to be looking at.
//
//go:embed testdata/AsqsApiStubs.java.template
var javaAPIStubsClass string // spring-javaformat:apply (tabs); space indents fail validate

// javaAPIStubsRelDir mirrors the smoke test's package, so both land in one place a reader finds.
var javaAPIStubsRelDir = filepath.Join("src", "test", "java", "com", "asqs", "e2e")

const javaAPIStubsFile = "AsqsApiStubs.java"

// csharpAPIStubs is the .NET equivalent. Written inline rather than embedded because C# takes
// spaces, so there is no formatter constraint of the kind the Java template exists for.
const csharpAPIStubs = `// Generated by ASQS e2e_framework_bootstrap — safe to edit or delete.
//
// Route-control helpers for E2E tests. Use them whenever a test asserts on something the
// application renders FROM ITS API: the test decides what comes back, so the assertion has a known
// answer and does not depend on a server being up.
//
// URL PATTERNS — read this before choosing one. A pattern is matched against the whole URL, so it
// can match the page navigation as well as the API call: a pattern of "**" + "/catalog*" matches
// both /api/catalog?q=x AND the page route /catalog, and fulfilling the navigation with JSON means
// the application never loads and every locator then "does not exist". Include the API's own path
// segment so only the request is intercepted.
using System.Threading.Tasks;
using Microsoft.Playwright;

namespace Asqs.E2E
{
    public static class AsqsApiStubs
    {
        /// <summary>Answer every matching request with <paramref name="json"/>. Register before the navigation that triggers it.</summary>
        public static Task StubJsonAsync(IPage page, string urlPattern, string json, int status = 200) =>
            page.RouteAsync(urlPattern, route => route.FulfillAsync(new RouteFulfillOptions
            {
                Status = status,
                ContentType = "application/json",
                Body = json,
            }));

        /// <summary>
        /// Answer after <paramref name="delayMs"/>, holding the request open in between.
        ///
        /// This is how a transient state becomes observable: a spinner shown while a request is in
        /// flight is gone the moment it settles, far sooner than any assertion can poll. IRoute has
        /// no delay member — the wait belongs inside the handler.
        /// </summary>
        public static Task StubJsonAfterAsync(IPage page, string urlPattern, string json, int delayMs, int status = 200) =>
            page.RouteAsync(urlPattern, async route =>
            {
                await Task.Delay(delayMs);
                await route.FulfillAsync(new RouteFulfillOptions
                {
                    Status = status,
                    ContentType = "application/json",
                    Body = json,
                });
            });

        /// <summary>Fail every matching request, for tests that assert on the application's error handling.</summary>
        public static Task StubErrorAsync(IPage page, string urlPattern, int status = 500) =>
            page.RouteAsync(urlPattern, route => route.FulfillAsync(new RouteFulfillOptions
            {
                Status = status,
                ContentType = "application/json",
                Body = "{\"message\":\"stubbed failure\"}",
            }));
    }
}
`

// writeJavaAPIStubs writes the Java route-control helpers beside the smoke test.
//
// Reached only from applyPlaywrightJavaBootstrap, which RunE2EBootstrap calls only when DetectE2E
// found no existing stack — so a project that already tests end-to-end never receives these. The
// owned-marker write is the second guard, and it is what lets a later run upgrade a file this one
// wrote without ever touching one the repository owns.
func writeJavaAPIStubs(moduleRoot string) (rel string, wrote bool, err error) {
	dir := filepath.Join(moduleRoot, javaAPIStubsRelDir)
	if mkErr := os.MkdirAll(dir, 0o755); mkErr != nil {
		return "", false, mkErr
	}
	p := filepath.Join(dir, javaAPIStubsFile)
	wrote, err = writeIfAbsentOrOwnedMarked(p, javaAPIStubsClass, asqsE2EGeneratedHeader)
	return p, wrote, err
}

// writeCSharpAPIStubs writes the .NET route-control helpers beside the smoke test.
func writeCSharpAPIStubs(e2eDir string) (rel string, wrote bool, err error) {
	if mkErr := os.MkdirAll(e2eDir, 0o755); mkErr != nil {
		return "", false, mkErr
	}
	p := filepath.Join(e2eDir, "AsqsApiStubs.cs")
	wrote, err = writeIfAbsentOrOwnedMarked(p, csharpAPIStubs, asqsE2EGeneratedHeader)
	return p, wrote, err
}

// apiStubsMarkerPresent reports whether a file carries this tool's ownership marker, so callers can
// tell a helper ASQS wrote from one the repository brought.
func apiStubsMarkerPresent(path string) bool {
	b, err := os.ReadFile(path)
	return err == nil && strings.Contains(string(b), asqsE2EGeneratedHeader)
}
