package testbootstrap

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const jestGlobalsDTSFile = "asqs-jest-globals.d.ts"

const jestGlobalsDTSContent = `// Generated by ASQS test_framework_bootstrap — Jest globals for TypeScript / ESLint. Safe to edit or delete.
/// <reference types="jest" />
`

// detectJestBootstrapIsTS is true when the repo should get the TypeScript Jest stack (@types/jest, ts-jest, tsconfig tweaks).
func detectJestBootstrapIsTS(repo, lang string) bool {
	lang = strings.ToLower(strings.TrimSpace(lang))
	if lang == "typescript" || lang == "ts" {
		return true
	}
	pkgDir := repo
	if d, err := resolveJSPackageDirForBootstrap(repo); err == nil {
		pkgDir = d
	}
	for _, base := range []string{pkgDir, repo} {
		if _, err := os.Stat(filepath.Join(base, "tsconfig.json")); err == nil {
			return true
		}
		matches, err := filepath.Glob(filepath.Join(base, "tsconfig*.json"))
		if err == nil && len(matches) > 0 {
			return true
		}
	}
	data, err := os.ReadFile(filepath.Join(pkgDir, "package.json"))
	if err != nil {
		return false
	}
	var root map[string]interface{}
	if json.Unmarshal(data, &root) != nil {
		return false
	}
	return packageJSONDeclaresTypeScript(root)
}

func packageJSONDeclaresTypeScript(root map[string]interface{}) bool {
	for _, key := range []string{"devDependencies", "dependencies", "peerDependencies", "optionalDependencies"} {
		m, _ := root[key].(map[string]interface{})
		if m == nil {
			continue
		}
		for _, name := range []string{"typescript", "tsx"} {
			if _, ok := m[name]; ok {
				return true
			}
		}
	}
	return false
}

// tsconfigFilesToPatch lists common repo-root configs that may type-check app/test sources (Angular/Nest/Vite/ESLint).
var tsconfigFilesToPatch = []string{
	"tsconfig.json",
	"tsconfig.app.json",
	"tsconfig.lib.json",
	"tsconfig.eslint.json",
}

// ensureJestTypeScriptTooling writes a Jest globals .d.ts and patches tsconfig(s) when needed so
// editors and tsc see describe/it/expect (explicit compilerOptions.types and restrictive include/files).
// Returns repo-relative paths of tsconfig files that were modified.
func ensureJestTypeScriptTooling(repoRoot, pkgDir string) (patchedTSConfigFiles []string, err error) {
	if err := writeJestGlobalsDTS(pkgDir); err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	for _, base := range []string{pkgDir, repoRoot} {
		for _, name := range tsconfigFilesToPatch {
			path := filepath.Join(base, name)
			if seen[path] {
				continue
			}
			seen[path] = true
			if _, err := os.Stat(path); err != nil {
				continue
			}
			ok, err := patchRootTSConfigForJest(path)
			if err != nil {
				return patchedTSConfigFiles, err
			}
			if ok {
				if rel, e := filepath.Rel(repoRoot, path); e == nil {
					patchedTSConfigFiles = append(patchedTSConfigFiles, filepath.ToSlash(rel))
				} else {
					patchedTSConfigFiles = append(patchedTSConfigFiles, name)
				}
			}
		}
	}
	return patchedTSConfigFiles, nil
}

func writeJestGlobalsDTS(dir string) error {
	p := filepath.Join(dir, jestGlobalsDTSFile)
	if b, err := os.ReadFile(p); err == nil {
		if strings.Contains(string(b), `reference types="jest"`) {
			return nil
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	return atomicWrite(p, []byte(jestGlobalsDTSContent))
}

func patchRootTSConfigForJest(tsconfigPath string) (bool, error) {
	raw, err := os.ReadFile(tsconfigPath)
	if err != nil {
		return false, err
	}
	stripped := stripTSConfigJSONComments(raw)
	stripped = stripTrailingJSONCommas(stripped)
	var root map[string]interface{}
	if err := json.Unmarshal(stripped, &root); err != nil {
		return false, nil
	}
	changed := false
	if co, ok := root["compilerOptions"].(map[string]interface{}); ok {
		if types, ok := co["types"].([]interface{}); ok {
			if !stringSliceContains(types, "jest") {
				co["types"] = append(types, "jest")
				changed = true
			}
		}
	}
	if inc, ok := root["include"].([]interface{}); ok {
		if !pathListReferencesJestGlobalsDTS(inc) {
			root["include"] = append(inc, jestGlobalsDTSFile)
			changed = true
		}
	}
	if files, ok := root["files"].([]interface{}); ok {
		if !pathListReferencesJestGlobalsDTS(files) {
			root["files"] = append(files, jestGlobalsDTSFile)
			changed = true
		}
	}
	if !changed {
		return false, nil
	}
	out, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return false, err
	}
	out = append(out, '\n')
	if err := atomicWrite(tsconfigPath, out); err != nil {
		return false, err
	}
	return true, nil
}

func stringSliceContains(slice []interface{}, want string) bool {
	for _, v := range slice {
		s, _ := v.(string)
		if s == want {
			return true
		}
	}
	return false
}

func pathListReferencesJestGlobalsDTS(inc []interface{}) bool {
	for _, v := range inc {
		s, _ := v.(string)
		s = strings.TrimSpace(s)
		if s == "" {
			continue
		}
		if strings.TrimPrefix(filepath.Base(s), "./") == jestGlobalsDTSFile {
			return true
		}
		if strings.Contains(s, jestGlobalsDTSFile) {
			return true
		}
		// Broad globs that already pull in repo-root .d.ts
		if s == "**/*" || s == "**/*.ts" || s == "**/*.tsx" {
			return true
		}
	}
	return false
}

func stripTSConfigJSONComments(b []byte) []byte {
	lines := bytes.Split(b, []byte("\n"))
	var out [][]byte
	for _, line := range lines {
		trim := bytes.TrimSpace(line)
		if len(trim) >= 2 && bytes.HasPrefix(trim, []byte("//")) {
			continue
		}
		out = append(out, line)
	}
	return bytes.Join(out, []byte("\n"))
}

var trailingCommaJSON = regexp.MustCompile(`,(\s*[}\]])`)

func stripTrailingJSONCommas(b []byte) []byte {
	return trailingCommaJSON.ReplaceAll(b, []byte("$1"))
}
