package testbootstrap

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// asqsGeneratedHeader marks files bootstrap owns, so a rewrite never clobbers a repo's own config.
const asqsGeneratedHeader = "Generated by ASQS test_framework_bootstrap"

// jsTestMatchGlobs is shared by both runners: __tests__ plus *.spec/*.test, minus the E2E roots.
const jsTestMatchGlobs = `'**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[jt]s?(x)'`

// renderJestConfig builds a jest.config.cjs for the profile.
//
// testEnvironment now comes from the profile. Hardcoding 'node' is what made every generated React
// component test fail on `document is not defined` no matter which libraries were installed.
func renderJestConfig(p jsTestProfile) string {
	var b strings.Builder
	fmt.Fprintf(&b, "/* %s — safe to edit or delete. */\n", asqsGeneratedHeader)
	b.WriteString("/** @type {import('jest').Config} */\nmodule.exports = {\n")

	switch {
	case p.Framework == JSFrameworkAngular:
		// The preset supplies the Angular transformer AND the jsdom environment; setting either here
		// would override it with a plain one.
		b.WriteString("  preset: 'jest-preset-angular',\n")
	case p.IsTS:
		b.WriteString("  preset: 'ts-jest',\n")
		fmt.Fprintf(&b, "  testEnvironment: '%s',\n", p.TestEnvironment)
	default:
		fmt.Fprintf(&b, "  testEnvironment: '%s',\n", p.TestEnvironment)
	}

	if p.SetupFile != "" {
		fmt.Fprintf(&b, "  setupFilesAfterEnv: ['<rootDir>/%s'],\n", p.SetupFile)
	}
	fmt.Fprintf(&b, "  testMatch: [%s,\n    /* CommonJS smoke tests run in \"type\":\"module\" packages without ESM/Jest VM wiring */\n    '**/__tests__/**/*.cjs'],\n", jsTestMatchGlobs)
	b.WriteString("  // Playwright/Cypress live under e2e/ and *.spec.ts; Jest must not run them.\n")
	b.WriteString("  testPathIgnorePatterns: ['/node_modules/', '<rootDir>/e2e/', '<rootDir>/cypress/'],\n")
	if p.IsTS {
		b.WriteString("  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],\n")
	} else {
		b.WriteString("  moduleFileExtensions: ['js', 'jsx', 'json'],\n")
	}
	b.WriteString("};\n")
	return b.String()
}

// renderVitestConfig builds a vitest.config for the profile.
//
// When the package already has a Vite config, the generated file MERGES it rather than replacing it.
// Vitest prefers vitest.config.* over vite.config.* and does not merge automatically, so a standalone
// file would silently drop the React plugin, the path aliases and every other build setting — the
// tests would then fail on JSX or on an unresolved '@/…' import.
func renderVitestConfig(p jsTestProfile, viteConfigRel string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "/* %s — safe to edit or delete. */\n", asqsGeneratedHeader)

	if viteConfigRel != "" {
		b.WriteString("import { defineConfig, mergeConfig } from 'vitest/config';\n")
		fmt.Fprintf(&b, "import viteConfig from './%s';\n\n", strings.TrimSuffix(viteConfigRel, filepath.Ext(viteConfigRel)))
		b.WriteString("// mergeConfig keeps the app's plugins, aliases and define settings; Vitest would\n")
		b.WriteString("// otherwise ignore vite.config entirely once this file exists.\n")
		b.WriteString("export default mergeConfig(\n  viteConfig,\n  defineConfig({\n")
	} else {
		b.WriteString("import { defineConfig } from 'vitest/config';\n\n")
		b.WriteString("export default defineConfig({\n")
	}

	indent := "    "
	if viteConfigRel == "" {
		indent = "  "
	}
	if len(p.ResolveConditions) > 0 {
		quoted := make([]string, 0, len(p.ResolveConditions))
		for _, c := range p.ResolveConditions {
			quoted = append(quoted, "'"+c+"'")
		}
		fmt.Fprintf(&b, "%sresolve: {\n%s  // Without this Svelte resolves to its server build and render() throws\n%s  // \"mount(...) is not available on the server\".\n%s  conditions: [%s],\n%s},\n",
			indent, indent, indent, indent, strings.Join(quoted, ", "), indent)
	}
	fmt.Fprintf(&b, "%stest: {\n", indent)
	fmt.Fprintf(&b, "%s  globals: true,\n", indent)
	fmt.Fprintf(&b, "%s  environment: '%s',\n", indent, p.TestEnvironment)
	if p.SetupFile != "" {
		fmt.Fprintf(&b, "%s  setupFiles: ['./%s'],\n", indent, p.SetupFile)
	}
	fmt.Fprintf(&b, "%s  include: ['**/__tests__/**/*.{test,spec}.{js,jsx,ts,tsx}', '**/*.{test,spec}.{js,jsx,ts,tsx}'],\n", indent)
	fmt.Fprintf(&b, "%s  exclude: ['**/node_modules/**', '**/dist/**', 'e2e/**', 'cypress/**'],\n", indent)
	fmt.Fprintf(&b, "%s},\n", indent)

	if viteConfigRel != "" {
		b.WriteString("  }),\n);\n")
	} else {
		b.WriteString("});\n")
	}
	return b.String()
}

// jsViteConfigRel returns the package's Vite config basename, or "".
func jsViteConfigRel(pkgDir string) string {
	for _, name := range []string{"vite.config.ts", "vite.config.mts", "vite.config.js", "vite.config.mjs"} {
		if fileExists(filepath.Join(pkgDir, name)) {
			return name
		}
	}
	return ""
}

// writeIfAbsentOrOwned writes path unless a file exists that ASQS did not generate.
func writeIfAbsentOrOwned(path, content string) (wrote bool, err error) {
	if b, rerr := os.ReadFile(path); rerr == nil {
		if !strings.Contains(string(b), asqsGeneratedHeader) {
			return false, nil // user-owned; never clobber
		}
		if string(b) == content {
			return false, nil
		}
	} else if !os.IsNotExist(rerr) {
		return false, rerr
	}
	return true, atomicWrite(path, []byte(content))
}

// writeJSRunnerConfig writes the profile's runner config file.
func writeJSRunnerConfig(pkgDir string, p jsTestProfile) (rel string, wrote bool, err error) {
	if p.ConfigFile == "" {
		return "", false, nil
	}
	var content string
	if p.Runner == JSRunnerVitest {
		content = renderVitestConfig(p, jsViteConfigRel(pkgDir))
	} else {
		content = renderJestConfig(p)
	}
	wrote, err = writeIfAbsentOrOwned(filepath.Join(pkgDir, p.ConfigFile), content)
	return p.ConfigFile, wrote, err
}

// jsSetupFileContent returns the per-framework setup module.
func jsSetupFileContent(p jsTestProfile) string {
	switch p.Framework {
	case JSFrameworkAngular:
		// setup-env/zone is the entry point every current preset line exposes; the older
		// 'jest-preset-angular/setup-jest' module was removed in v15+.
		return fmt.Sprintf("// %s — safe to edit or delete.\nimport { setupZoneTestEnv } from 'jest-preset-angular/setup-env/zone';\n\nsetupZoneTestEnv();\n", asqsGeneratedHeader)
	case JSFrameworkReact, JSFrameworkVue, JSFrameworkSvelte:
		return fmt.Sprintf("// %s — safe to edit or delete.\nimport '@testing-library/jest-dom';\n", asqsGeneratedHeader)
	default:
		return ""
	}
}

// writeJSSetupFile writes the profile's setup module when it has one.
func writeJSSetupFile(pkgDir string, p jsTestProfile) (rel string, wrote bool, err error) {
	if p.SetupFile == "" {
		return "", false, nil
	}
	content := jsSetupFileContent(p)
	if content == "" {
		return "", false, nil
	}
	wrote, err = writeIfAbsentOrOwned(filepath.Join(pkgDir, p.SetupFile), content)
	return p.SetupFile, wrote, err
}

// angularTsconfigSpec is the test tsconfig jest-preset-angular resolves by default.
//
// The preset points ts-jest at <rootDir>/tsconfig.spec.json. The Angular CLI generates that file for
// projects created with a test target, but a project with no test setup at all — exactly the case
// bootstrap exists for — does not have one, and Jest fails with "File not found:
// <rootDir>/tsconfig.spec.json" before running a single test.
//
// module/moduleResolution are overridden together on purpose: Angular's own tsconfig uses
// "module": "ES2022" with "moduleResolution": "bundler", and Jest needs CommonJS output. Setting
// module without moduleResolution trips TS5095 ("bundler" requires module preserve/esnext).
const angularTsconfigSpec = `{
  /* ` + asqsGeneratedHeader + ` — safe to edit or delete. */
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "module": "CommonJS",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "types": ["jest"]
  },
  "include": ["src/**/*.spec.ts", "src/**/*.d.ts", "__tests__/**/*.ts"]
}
`

// writeAngularTsconfigSpec creates tsconfig.spec.json when the Angular profile needs one.
func writeAngularTsconfigSpec(pkgDir string, p jsTestProfile) (rel string, wrote bool, err error) {
	if p.Framework != JSFrameworkAngular {
		return "", false, nil
	}
	rel = "tsconfig.spec.json"
	wrote, err = writeIfAbsentOrOwned(filepath.Join(pkgDir, rel), angularTsconfigSpec)
	return rel, wrote, err
}
