package testbootstrap

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// asqsE2EGeneratedHeader marks files the E2E bootstrap owns.
//
// Distinct from asqsGeneratedHeader on purpose: the two bootstraps write different files and either
// may run without the other, so a single marker would let one claim ownership of the other's output.
const asqsE2EGeneratedHeader = "Generated by ASQS e2e_framework_bootstrap"

// playwrightWebServer is how to bring the application up so a browser test can navigate to it.
//
// Zero value means "could not be named with confidence", and renderPlaywrightConfig then omits both
// webServer and baseURL. That is deliberate: a wrong command hangs every E2E run until
// webServer.timeout expires, which is worse than the honest navigation failure it would replace.
type playwrightWebServer struct {
	Command string
	Port    int
}

func (w playwrightWebServer) ok() bool { return w.Command != "" && w.Port > 0 }

// devServerPortForFramework is the port each framework's dev server listens on by default.
//
// Only frameworks whose default is stable across major versions are listed. Anything absent yields
// no webServer rather than a guess.
func devServerPortForFramework(det jsFrameworkDetection) int {
	if det.Framework == JSFrameworkAngular {
		return 4200
	}
	// Vite owns the port for every framework it serves, regardless of which one that is.
	if det.ViteMajor != 0 {
		return 5173
	}
	return 0
}

// devServerScript picks the package.json script that starts the app.
//
// "start" first, then "dev": Angular CLI generates `start`, Vite templates generate `dev`, and a
// repo carrying both means the two agree.
func devServerScript(scripts map[string]string) string {
	for _, name := range []string{"start", "dev"} {
		if strings.TrimSpace(scripts[name]) != "" {
			return name
		}
	}
	return ""
}

// detectPlaywrightWebServer resolves how to serve pkgDir's app during an E2E run.
//
// Returns the zero value whenever either half is unknown. Both halves come from the repository
// itself — package.json scripts and the same framework detection the unit bootstrap uses — so
// nothing here is inferred from the ASQS side.
func detectPlaywrightWebServer(pkgDir, lang string) playwrightWebServer {
	pkg, err := readJSPackageJSON(pkgDir)
	if err != nil {
		return playwrightWebServer{}
	}
	script := devServerScript(pkg.Scripts)
	if script == "" {
		return playwrightWebServer{}
	}
	det, derr := detectJSFramework(pkgDir, lang)
	if derr != nil {
		return playwrightWebServer{}
	}
	port := devServerPortForFramework(det)
	if port == 0 {
		return playwrightWebServer{}
	}
	// `--` before the flag is required for npm and pnpm to forward it to the script rather than
	// consume it themselves; yarn forwards trailing args without it.
	pm := detectPackageManager(pkgDir)
	cmd := fmt.Sprintf("%s run %s -- --port %d", pm, script, port)
	if pm == PMYarn {
		cmd = fmt.Sprintf("yarn %s --port %d", script, port)
	}
	return playwrightWebServer{Command: cmd, Port: port}
}

// renderPlaywrightConfig builds playwright.config.ts for one package directory.
//
// The use.baseURL + webServer pair is the whole point of this file having a renderer rather than
// being a constant. Without them, a generated spec's `page.goto('/checkout')` fails with
// "Cannot navigate to invalid URL" before the application is ever exercised: run
// api-874025913eb1599cccc74ae04a5ac46b lost six of its seven E2E tests that way, and the fixer
// could not repair it because playwright.config.ts is not a writable artifact — it is not even in
// the fixer's read-only context, so no repair round could see what was missing.
//
// stdout/stderr are piped so a dev server that fails to boot says so in the E2E failure output the
// fixer reads, instead of surfacing as an unexplained navigation timeout.
func renderPlaywrightConfig(ws playwrightWebServer) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s — safe to edit or delete.\n", asqsE2EGeneratedHeader)
	b.WriteString("import { defineConfig, devices } from '@playwright/test';\n\n")
	b.WriteString("export default defineConfig({\n")
	b.WriteString("  testDir: './e2e',\n")
	b.WriteString("  fullyParallel: true,\n")
	// process.env['CI'], not process.env['CI']: Angular's generated tsconfig sets
	// noPropertyAccessFromIndexSignature, under which dotted access to an index-signature property
	// is TS4111. Run api-7e4930f7306db0a480d4ced6c4107ede reported it four times against this file
	// once the post-generate type-check gate was switched on. Bracket access is valid under every
	// tsconfig, so it costs nothing where the flag is off.
	b.WriteString("  forbidOnly: !!process.env['CI'],\n")
	b.WriteString("  retries: process.env['CI'] ? 2 : 0,\n")
	b.WriteString("  workers: process.env['CI'] ? 1 : undefined,\n")
	b.WriteString("  reporter: 'list',\n")
	b.WriteString("  use: {\n")
	if ws.ok() {
		fmt.Fprintf(&b, "    baseURL: 'http://localhost:%d',\n", ws.Port)
	}
	b.WriteString("    trace: 'on-first-retry',\n")
	b.WriteString("  },\n")
	b.WriteString("  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],\n")
	if ws.ok() {
		b.WriteString("  webServer: {\n")
		fmt.Fprintf(&b, "    command: '%s',\n", ws.Command)
		// localhost, not 127.0.0.1: it is what both `ng serve` and `vite` bind by default, so the
		// readiness probe resolves the same way the server does.
		fmt.Fprintf(&b, "    url: 'http://localhost:%d',\n", ws.Port)
		b.WriteString("    reuseExistingServer: !process.env['CI'],\n")
		// 120s, not Playwright's 60s default: a cold Angular or Vite build from an unwarmed cache
		// regularly exceeds a minute inside a container.
		b.WriteString("    timeout: 120_000,\n")
		b.WriteString("    stdout: 'pipe',\n")
		b.WriteString("    stderr: 'pipe',\n")
		b.WriteString("  },\n")
	}
	b.WriteString("});\n")
	return b.String()
}

// Minimal spec so `playwright test --list` (bootstrap verify) finds at least one test. Cypress bootstrap already writes smoke.cy.ts; Playwright must do the same.
const playwrightSmokeSpec = `// Generated by ASQS e2e_framework_bootstrap — safe to edit or delete.
// Group tests with test.describe(...) from '@playwright/test' — not global describe() (Jest/Cypress).
import { test, expect } from '@playwright/test';

test.describe('smoke', () => {
  test('bootstrap smoke', () => {
    expect(true).toBeTruthy();
  });
});
`

// writePlaywrightConfig writes playwright.config.ts, leaving a repository's own config alone.
//
// writeIfAbsentOrOwnedMarked rather than the plain "skip when the file exists" this used to do: the
// generated tests ship, so an ASQS-written config from an earlier run is present on the next one,
// and a bare existence check pinned every repository to the first version ASQS ever wrote for it.
func writePlaywrightConfig(dir, lang string) error {
	p := filepath.Join(dir, "playwright.config.ts")
	_, err := writeIfAbsentOrOwnedMarked(p, renderPlaywrightConfig(detectPlaywrightWebServer(dir, lang)), asqsE2EGeneratedHeader)
	return err
}

// writePlaywrightSmokeSpec writes e2e/smoke.spec.ts if missing (matches testDir in generated config).
func writePlaywrightSmokeSpec(dir string) error {
	e2eDir := filepath.Join(dir, "e2e")
	if err := os.MkdirAll(e2eDir, 0755); err != nil {
		return err
	}
	p := filepath.Join(e2eDir, "smoke.spec.ts")
	if _, err := os.Stat(p); err == nil {
		return nil
	}
	return atomicWrite(p, []byte(playwrightSmokeSpec))
}

// E2EAppPort reports the port the generated Playwright config serves the application on, or 0 when
// no web server could be named for this repository.
//
// Exported for the generator, which needs to exclude the app's own origin when warning that the
// application calls a backend nothing will be serving during the suite. internal/orchestrator cannot
// import this package (it is imported BY it), so the workflow layer reads the port here and passes
// it down.
func E2EAppPort(repo, lang string) int {
	pkgDir, err := resolveJSPackageDirForBootstrap(strings.TrimSpace(repo))
	if err != nil {
		return 0
	}
	return detectPlaywrightWebServer(pkgDir, lang).Port
}
