package testbootstrap

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// asqsE2EGeneratedHeader marks files the E2E bootstrap owns.
//
// Distinct from asqsGeneratedHeader on purpose: the two bootstraps write different files and either
// may run without the other, so a single marker would let one claim ownership of the other's output.
const asqsE2EGeneratedHeader = "Generated by ASQS e2e_framework_bootstrap"

// playwrightWebServer is how to bring the application up so a browser test can navigate to it.
//
// Zero value means "could not be named with confidence", and renderPlaywrightConfig then omits both
// webServer and baseURL. That is deliberate: a wrong command hangs every E2E run until
// webServer.timeout expires, which is worse than the honest navigation failure it would replace.
type playwrightWebServer struct {
	Command string
	Port    int
}

func (w playwrightWebServer) ok() bool { return w.Command != "" && w.Port > 0 }

// devServerPortForFramework is the port each framework's dev server listens on by default.
//
// Only frameworks whose default is stable across major versions are listed. Anything absent yields
// no webServer rather than a guess.
func devServerPortForFramework(det jsFrameworkDetection) int {
	if det.Framework == JSFrameworkAngular {
		return 4200
	}
	// Vite owns the port for every framework it serves, regardless of which one that is.
	if det.ViteMajor != 0 {
		return 5173
	}
	return 0
}

// devServerScript picks the package.json script that starts the app.
//
// "start" first, then "dev": Angular CLI generates `start`, Vite templates generate `dev`, and a
// repo carrying both means the two agree.
func devServerScript(scripts map[string]string) string {
	for _, name := range []string{"start", "dev"} {
		if strings.TrimSpace(scripts[name]) != "" {
			return name
		}
	}
	return ""
}

// detectPlaywrightWebServer resolves how to serve pkgDir's app during an E2E run.
//
// Returns the zero value whenever either half is unknown. Both halves come from the repository
// itself — package.json scripts and the same framework detection the unit bootstrap uses — so
// nothing here is inferred from the ASQS side.
func detectPlaywrightWebServer(pkgDir, lang string) playwrightWebServer {
	pkg, err := readJSPackageJSON(pkgDir)
	if err != nil {
		return playwrightWebServer{}
	}
	script := devServerScript(pkg.Scripts)
	if script == "" {
		return playwrightWebServer{}
	}
	det, derr := detectJSFramework(pkgDir, lang)
	if derr != nil {
		return playwrightWebServer{}
	}
	port := devServerPortForFramework(det)
	if port == 0 {
		return playwrightWebServer{}
	}
	// `--` before the flag is required for npm and pnpm to forward it to the script rather than
	// consume it themselves; yarn forwards trailing args without it.
	pm := detectPackageManager(pkgDir)
	cmd := fmt.Sprintf("%s run %s -- --port %d", pm, script, port)
	if pm == PMYarn {
		cmd = fmt.Sprintf("yarn %s --port %d", script, port)
	}
	return playwrightWebServer{Command: cmd, Port: port}
}

// renderPlaywrightConfig builds playwright.config.ts for one package directory.
//
// The use.baseURL + webServer pair is the whole point of this file having a renderer rather than
// being a constant. Without them, a generated spec's `page.goto('/checkout')` fails with
// "Cannot navigate to invalid URL" before the application is ever exercised: run
// api-874025913eb1599cccc74ae04a5ac46b lost six of its seven E2E tests that way, and the fixer
// could not repair it because playwright.config.ts is not a writable artifact — it is not even in
// the fixer's read-only context, so no repair round could see what was missing.
//
// stdout/stderr are piped so a dev server that fails to boot says so in the E2E failure output the
// fixer reads, instead of surfacing as an unexplained navigation timeout.
func renderPlaywrightConfig(ws playwrightWebServer, extraTestMatch []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s — safe to edit or delete.\n", asqsE2EGeneratedHeader)
	b.WriteString("import { defineConfig, devices } from '@playwright/test';\n\n")
	b.WriteString("export default defineConfig({\n")
	b.WriteString("  testDir: './e2e',\n")
	if len(extraTestMatch) > 0 {
		// Playwright's default restated first, so the extra patterns ADD to it.
		pats := append([]string{playwrightDefaultTestMatch}, extraTestMatch...)
		for i := range pats {
			pats[i] = "'" + pats[i] + "'"
		}
		fmt.Fprintf(&b, "  testMatch: [%s],\n", strings.Join(pats, ", "))
	}
	b.WriteString("  fullyParallel: true,\n")
	// process.env['CI'], not process.env['CI']: Angular's generated tsconfig sets
	// noPropertyAccessFromIndexSignature, under which dotted access to an index-signature property
	// is TS4111. Run api-7e4930f7306db0a480d4ced6c4107ede reported it four times against this file
	// once the post-generate type-check gate was switched on. Bracket access is valid under every
	// tsconfig, so it costs nothing where the flag is off.
	b.WriteString("  forbidOnly: !!process.env['CI'],\n")
	b.WriteString("  retries: process.env['CI'] ? 2 : 0,\n")
	b.WriteString("  workers: process.env['CI'] ? 1 : undefined,\n")
	b.WriteString("  reporter: 'list',\n")
	b.WriteString("  use: {\n")
	if ws.ok() {
		fmt.Fprintf(&b, "    baseURL: 'http://localhost:%d',\n", ws.Port)
	}
	b.WriteString("    trace: 'on-first-retry',\n")
	b.WriteString("  },\n")
	b.WriteString("  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],\n")
	if ws.ok() {
		b.WriteString("  webServer: {\n")
		fmt.Fprintf(&b, "    command: '%s',\n", ws.Command)
		// localhost, not 127.0.0.1: it is what both `ng serve` and `vite` bind by default, so the
		// readiness probe resolves the same way the server does.
		fmt.Fprintf(&b, "    url: 'http://localhost:%d',\n", ws.Port)
		b.WriteString("    reuseExistingServer: !process.env['CI'],\n")
		// 120s, not Playwright's 60s default: a cold Angular or Vite build from an unwarmed cache
		// regularly exceeds a minute inside a container.
		b.WriteString("    timeout: 120_000,\n")
		b.WriteString("    stdout: 'pipe',\n")
		b.WriteString("    stderr: 'pipe',\n")
		b.WriteString("  },\n")
	}
	b.WriteString("});\n")
	return b.String()
}

// Minimal spec so `playwright test --list` (bootstrap verify) finds at least one test. Cypress bootstrap already writes smoke.cy.ts; Playwright must do the same.
const playwrightSmokeSpec = `// Generated by ASQS e2e_framework_bootstrap — safe to edit or delete.
// Group tests with test.describe(...) from '@playwright/test' — not global describe() (Jest/Cypress).
import { test, expect } from '@playwright/test';

test.describe('smoke', () => {
  test('bootstrap smoke', () => {
    expect(true).toBeTruthy();
  });
});
`

// writePlaywrightConfig writes playwright.config.ts, leaving a repository's own config alone.
//
// writeIfAbsentOrOwnedMarked rather than the plain "skip when the file exists" this used to do: the
// generated tests ship, so an ASQS-written config from an earlier run is present on the next one,
// and a bare existence check pinned every repository to the first version ASQS ever wrote for it.
func writePlaywrightConfig(dir, lang string) error {
	p := filepath.Join(dir, "playwright.config.ts")
	_, err := writeIfAbsentOrOwnedMarked(p, renderPlaywrightConfig(detectPlaywrightWebServer(dir, lang), extraPlaywrightTestMatch(dir)), asqsE2EGeneratedHeader)
	return err
}

// playwrightDefaultTestMatch is Playwright's own default testMatch, restated verbatim so a generated
// config that needs one more pattern keeps everything the default already covered.
const playwrightDefaultTestMatch = "**/*.@(spec|test).?(c|m)[jt]s?(x)"

// playwrightE2ESpecSuffixTestMatch covers the `*.e2e-spec.ts` naming Angular CLI projects inherited
// from Protractor and kept for their e2e/ folder.
const playwrightE2ESpecSuffixTestMatch = "**/*.e2e-spec.?(c|m)[jt]s"

// e2eSpecSuffixRE matches the file names playwrightE2ESpecSuffixTestMatch is for.
var e2eSpecSuffixRE = regexp.MustCompile(`(?i)\.e2e-spec\.[cm]?[jt]s$`)

// extraPlaywrightTestMatch returns the testMatch patterns the generated config needs beyond
// Playwright's default so that every spec ASQS treats as an E2E artifact is actually executed.
//
// The indexer classifies `e2e/**/*.e2e-spec.ts` as an E2E spec and the planner hands it to the
// generator as an E2E_SPEC gap, but Playwright's default testMatch — `*.@(spec|test).*` — does not
// match that suffix. The asqs-core run of 2026-09-03 wrote `e2e/smoke.e2e-spec.ts` as an artifact,
// ran 8 tests (the generated route specs plus the bootstrap smoke), and would have shipped that file
// without it ever having been loaded.
//
// Only added when at least one such file under e2e/ imports `@playwright/test`, and never when one
// of them is a Protractor spec (`from 'protractor'`): Protractor is the origin of the suffix, its
// specs drive `browser`/`element` globals Playwright does not provide, and loading them would fail
// the whole E2E run at import.
//
// The import requirement is what keeps the bootstrap's own verification honest. The run of
// 2026-09-04 matched the fixture's `e2e/smoke.e2e-spec.ts` — a bare `test(` with no import — and
// `playwright test --list` failed with `ReferenceError: test is not defined`, so the bootstrap
// reported itself failed although every file it writes was in place. A file that gains the import
// later (the generator extends it, see EnsurePlaywrightImport) is picked up by
// RefreshPlaywrightConfig before the evaluation runs.
func extraPlaywrightTestMatch(pkgDir string) []string {
	root := filepath.Join(pkgDir, "e2e")
	playwright := false
	protractor := false
	_ = filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			if d.Name() == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		if !e2eSpecSuffixRE.MatchString(d.Name()) {
			return nil
		}
		b, rerr := os.ReadFile(p)
		if rerr != nil {
			return nil
		}
		if protractorImportRE.Match(b) {
			protractor = true
		}
		if playwrightTestImportRE.Match(b) {
			playwright = true
		}
		return nil
	})
	if !playwright || protractor {
		return nil
	}
	return []string{playwrightE2ESpecSuffixTestMatch}
}

// protractorImportRE matches an import or require of the protractor package.
var protractorImportRE = regexp.MustCompile(`(?m)(?:from\s+|require\(\s*)['"]protractor['"]`)

// playwrightTestImportRE matches an import or require of @playwright/test.
var playwrightTestImportRE = regexp.MustCompile(`(?m)(?:from\s+|require\(\s*)['"]@playwright/test['"]`)

// playwrightSpecUsesTestAPIRE matches the Playwright test API a spec file calls: `test(`,
// `test.describe(`, `test.beforeEach(`, `expect(`.
var playwrightSpecUsesTestAPIRE = regexp.MustCompile(`(?m)^\s*(?:test(?:\.\w+)*|expect)\s*\(`)

// EnsurePlaywrightImport makes a Playwright spec file import the test API it calls.
//
// The generator extends an existing E2E spec in place, and a fixture file that opened with a bare
// `test(` (no import) stayed that way after the merge: the run of 2026-09-04 loaded
// `e2e/smoke.e2e-spec.ts` and failed with `ReferenceError: test is not defined`, spending the first
// post-discard repair round on the one line this adds. Idempotent: a file that already imports
// `@playwright/test`, or calls no test API, is returned unchanged. Returns whether it wrote.
func EnsurePlaywrightImport(specPath string) (bool, error) {
	b, err := os.ReadFile(specPath)
	if err != nil {
		return false, err
	}
	s := string(b)
	if playwrightTestImportRE.MatchString(s) || !playwrightSpecUsesTestAPIRE.MatchString(s) {
		return false, nil
	}
	if protractorImportRE.MatchString(s) {
		return false, nil
	}
	line := "import { test, expect } from '@playwright/test';\n"
	// After a leading comment block or directive, before the first statement.
	out := line + s
	if strings.HasPrefix(s, "//") || strings.HasPrefix(s, "/*") {
		// Keep a file-opening comment where it is.
		i := strings.Index(s, "\n")
		if strings.HasPrefix(s, "/*") {
			if j := strings.Index(s, "*/"); j >= 0 {
				i = j + 2
				if k := strings.Index(s[i:], "\n"); k >= 0 {
					i += k
				}
			}
		}
		if i >= 0 {
			out = s[:i+1] + line + s[i+1:]
		}
	}
	return true, atomicWrite(specPath, []byte(out))
}

// RefreshPlaywrightConfig re-renders an ASQS-owned playwright.config.ts for the repository's JS
// package directory, so that testMatch reflects the spec files as they are NOW — after generation
// has extended or added them. A repository's own config is never touched, and nothing is created
// where no owned config exists. Returns the repo-relative config path when it was rewritten.
func RefreshPlaywrightConfig(repo, lang string) (string, error) {
	pkgDir, err := resolveJSPackageDirForBootstrap(repo)
	if err != nil {
		return "", nil
	}
	p := filepath.Join(pkgDir, "playwright.config.ts")
	b, rerr := os.ReadFile(p)
	if rerr != nil || !strings.Contains(string(b), asqsE2EGeneratedHeader) {
		return "", nil
	}
	wrote, werr := writeIfAbsentOrOwnedMarked(p, renderPlaywrightConfig(detectPlaywrightWebServer(pkgDir, lang), extraPlaywrightTestMatch(pkgDir)), asqsE2EGeneratedHeader)
	if werr != nil || !wrote {
		return "", werr
	}
	rel, _ := filepath.Rel(repo, p)
	return filepath.ToSlash(rel), nil
}

// writePlaywrightSmokeSpec writes e2e/smoke.spec.ts if missing (matches testDir in generated config).
func writePlaywrightSmokeSpec(dir string) error {
	e2eDir := filepath.Join(dir, "e2e")
	if err := os.MkdirAll(e2eDir, 0755); err != nil {
		return err
	}
	p := filepath.Join(e2eDir, "smoke.spec.ts")
	if _, err := os.Stat(p); err == nil {
		return nil
	}
	return atomicWrite(p, []byte(playwrightSmokeSpec))
}

// E2EAppPort reports the port the generated Playwright config serves the application on, or 0 when
// no web server could be named for this repository.
//
// Exported for the generator, which needs to exclude the app's own origin when warning that the
// application calls a backend nothing will be serving during the suite. internal/orchestrator cannot
// import this package (it is imported BY it), so the workflow layer reads the port here and passes
// it down.
func E2EAppPort(repo, lang string) int {
	pkgDir, err := resolveJSPackageDirForBootstrap(strings.TrimSpace(repo))
	if err != nil {
		return 0
	}
	return detectPlaywrightWebServer(pkgDir, lang).Port
}
