package testbootstrap

import (
	"os"
	"path/filepath"
	"strings"
)

// playwrightSupportRel is where the generated helpers live, relative to the package root. Under the
// Playwright testDir but in its own directory, so `*.spec.ts` collection never picks it up.
const playwrightSupportRel = "e2e/support/api.ts"

// playwrightSupportAPI is a route-control module for generated specs.
//
// Only three functions, and all three are the same concern: deciding what the application receives
// from its API. That concern is the difference between an E2E suite that tests something and one
// that asserts on an error state it never described — in run api-b59d58ba67f66bee9364c050f4c319cc
// every remaining failure was an assertion on data the app could not have, because nothing served
// the API the app is configured against and no spec supplied it.
//
// Proven, not guessed: both of the run's stuck assertions pass against the UNMODIFIED application
// using exactly these two shapes — fulfil for `catalog-results`, delayed fulfil for the
// `catalog-loading` state that is otherwise true for microseconds.
//
// The doc comment carries the URL-pattern warning because that is where someone writing a spec will
// read it, and it is a trap with a misleading symptom: `**/catalog*` also matches the PAGE route
// `/catalog`, so Playwright fulfils the navigation itself with JSON, the application never boots,
// and the failure reads as "element not found" — a bug in the app, apparently, rather than in the
// pattern.
const playwrightSupportAPI = `// Generated by ASQS e2e_framework_bootstrap — safe to edit or delete.
//
// Route-control helpers for E2E specs. Use them whenever a test asserts on something the
// application renders FROM ITS API: the test decides what comes back, so the assertion has a known
// answer and does not depend on a server being up.
//
// URL PATTERNS — read this before choosing one. A pattern is matched against the whole URL, so it
// can match the page navigation as well as the API call. ` + "`'**/catalog*'`" + ` matches both
// ` + "`/api/catalog?q=x`" + ` AND the page route ` + "`/catalog`" + `; fulfilling the navigation with JSON means the
// application never loads and every locator then "does not exist". Include the API's own path
// segment — ` + "`'**/api/catalog*'`" + ` — so only the request is intercepted.
import type { Page } from '@playwright/test';

/** Answer every matching request with ` + "`body`" + ` as JSON. Register before the navigation that triggers it. */
export async function stubJson(page: Page, urlPattern: string, body: unknown, status = 200): Promise<void> {
  await page.route(urlPattern, (route) => route.fulfill({ status, json: body }));
}

/**
 * Answer after ` + "`delayMs`" + `, holding the request open in between.
 *
 * This is how a transient state becomes observable. A spinner shown while a request is in flight is
 * gone the moment it settles — against a stubbed or absent backend that is the next tick, far
 * sooner than any assertion can poll — so a test that asserts on one must hold the response.
 */
export async function stubJsonAfter(
  page: Page,
  urlPattern: string,
  body: unknown,
  delayMs: number,
  status = 200,
): Promise<void> {
  await page.route(urlPattern, async (route) => {
    await new Promise((resolve) => setTimeout(resolve, delayMs));
    await route.fulfill({ status, json: body });
  });
}

/** Fail every matching request, for specs that assert on the application's error handling. */
export async function stubError(page: Page, urlPattern: string, status = 500, body: unknown = { message: 'stubbed failure' }): Promise<void> {
  await page.route(urlPattern, (route) => route.fulfill({ status, json: body }));
}
`

// writePlaywrightSupportHelpers writes the route-control module, leaving a repository's own file
// alone.
//
// Reached only from applyPlaywrightBootstrap, which RunE2EBootstrap calls only when DetectE2E found
// no existing stack — so a project that already tests end-to-end never receives these. The
// owned-marker write is the second guard: it covers a repository that has its own e2e/support/api.ts
// without a detectable E2E stack, and it lets a later run upgrade a file this one wrote.
func writePlaywrightSupportHelpers(dir string) (rel string, wrote bool, err error) {
	p := filepath.Join(dir, filepath.FromSlash(playwrightSupportRel))
	if mkErr := os.MkdirAll(filepath.Dir(p), 0o755); mkErr != nil {
		return playwrightSupportRel, false, mkErr
	}
	wrote, err = writeIfAbsentOrOwnedMarked(p, playwrightSupportAPI, asqsE2EGeneratedHeader)
	return playwrightSupportRel, wrote, err
}

// PlaywrightSupportModule returns the repo-relative import path of the ASQS-written route-control
// module when it is present, or "" when it is not.
//
// The generator names it in the prompt only when it exists, so a repository that brought its own
// E2E setup is never told to import a file it does not have.
func PlaywrightSupportModule(repo string) string {
	if repo == "" {
		return ""
	}
	pkgDir, err := resolveJSPackageDirForBootstrap(repo)
	if err != nil {
		return ""
	}
	b, rerr := os.ReadFile(filepath.Join(pkgDir, filepath.FromSlash(playwrightSupportRel)))
	if rerr != nil || !strings.Contains(string(b), asqsE2EGeneratedHeader) {
		return ""
	}
	return playwrightSupportRel
}
