package testbootstrap

import (
	"os"
	"path/filepath"
)

const playwrightConfigTS = `// Generated by ASQS e2e_framework_bootstrap — safe to edit or delete.
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'list',
  use: {
    trace: 'on-first-retry',
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
});
`

// Minimal spec so `playwright test --list` (bootstrap verify) finds at least one test. Cypress bootstrap already writes smoke.cy.ts; Playwright must do the same.
const playwrightSmokeSpec = `// Generated by ASQS e2e_framework_bootstrap — safe to edit or delete.
// Group tests with test.describe(...) from '@playwright/test' — not global describe() (Jest/Cypress).
import { test, expect } from '@playwright/test';

test.describe('smoke', () => {
  test('bootstrap smoke', () => {
    expect(true).toBeTruthy();
  });
});
`

// writePlaywrightConfig writes playwright.config.ts if missing.
func writePlaywrightConfig(dir string) error {
	p := filepath.Join(dir, "playwright.config.ts")
	if _, err := os.Stat(p); err == nil {
		return nil
	}
	return atomicWrite(p, []byte(playwrightConfigTS))
}

// writePlaywrightSmokeSpec writes e2e/smoke.spec.ts if missing (matches testDir in generated config).
func writePlaywrightSmokeSpec(dir string) error {
	e2eDir := filepath.Join(dir, "e2e")
	if err := os.MkdirAll(e2eDir, 0755); err != nil {
		return err
	}
	p := filepath.Join(e2eDir, "smoke.spec.ts")
	if _, err := os.Stat(p); err == nil {
		return nil
	}
	return atomicWrite(p, []byte(playwrightSmokeSpec))
}
