package pipeline

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

type e2ePrepAuditor struct {
	steps []string
	msgs  []string
}

func (a *e2ePrepAuditor) Log(_ context.Context, step string, payload interface{}) {
	a.steps = append(a.steps, step)
	if m, ok := payload.(map[string]interface{}); ok {
		s, _ := m["message"].(string)
		a.msgs = append(a.msgs, s)
	}
}
func (a *e2ePrepAuditor) LogError(ctx context.Context, step string, payload interface{}) {
	a.Log(ctx, step, payload)
}

func writePrepFile(t *testing.T, dir, rel, body string) {
	t.Helper()
	full := filepath.Join(dir, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

// Run of 2026-09-04: the extended e2e/smoke.e2e-spec.ts kept the fixture's bare `test(` and the
// bootstrap-time config did not match the file. Both are repaired before the E2E pass.
func TestPrepareGeneratedPlaywrightSpecs_importsAndRefreshesConfig(t *testing.T) {
	dir := t.TempDir()
	writePrepFile(t, dir, "package.json", `{"name":"x","scripts":{"start":"ng serve"},"devDependencies":{"@angular/core":"^19.2.0","@playwright/test":"1.49.1"}}`)
	writePrepFile(t, dir, "playwright.config.ts", "// Generated by ASQS e2e_framework_bootstrap — safe to edit or delete.\nexport default {};\n")
	writePrepFile(t, dir, "e2e/smoke.e2e-spec.ts", "// marker\ntest.describe('smoke', () => {\n  test('loads', async ({ page }) => { await page.goto('/'); });\n});\n")
	writePrepFile(t, dir, "e2e/routes/catalog.spec.ts", "import { test, expect } from '@playwright/test';\ntest('c', async ({ page }) => { await page.goto('/catalog'); });\n")
	a := &e2ePrepAuditor{}
	prepareGeneratedPlaywrightSpecs(context.Background(), dir, "typescript", "playwright", []string{"e2e/smoke.e2e-spec.ts", "e2e/routes/catalog.spec.ts", "e2e/refused.spec.ts"}, a)

	b, _ := os.ReadFile(filepath.Join(dir, "e2e", "smoke.e2e-spec.ts"))
	if !strings.Contains(string(b), "import { test, expect } from '@playwright/test';") {
		t.Fatalf("import not added:\n%s", b)
	}
	c, _ := os.ReadFile(filepath.Join(dir, "e2e", "routes", "catalog.spec.ts"))
	if strings.Count(string(c), "@playwright/test") != 1 {
		t.Error("a spec that already imports must be left alone")
	}
	cfg, _ := os.ReadFile(filepath.Join(dir, "playwright.config.ts"))
	if !strings.Contains(string(cfg), "**/*.e2e-spec.?(c|m)[jt]s") {
		t.Fatalf("config not refreshed with the suffix pattern:\n%s", cfg)
	}
	joined := strings.Join(a.steps, ",")
	if !strings.Contains(joined, "generate.e2e_playwright_import") || !strings.Contains(joined, "generate.playwright_config_refresh") {
		t.Errorf("expected both audit events, got %v", a.steps)
	}
	if _, err := os.Stat(filepath.Join(dir, "e2e", "refused.spec.ts")); err == nil {
		t.Error("a missing artifact must not be created")
	}
}

func TestPrepareGeneratedPlaywrightSpecs_noopOutsidePlaywrightJS(t *testing.T) {
	dir := t.TempDir()
	writePrepFile(t, dir, "e2e/smoke.e2e-spec.ts", "test('x', () => {});\n")
	a := &e2ePrepAuditor{}
	prepareGeneratedPlaywrightSpecs(context.Background(), dir, "typescript", "cypress", []string{"e2e/smoke.e2e-spec.ts"}, a)
	prepareGeneratedPlaywrightSpecs(context.Background(), dir, "java", "playwright", []string{"e2e/smoke.e2e-spec.ts"}, a)
	prepareGeneratedPlaywrightSpecs(context.Background(), dir, "typescript", "playwright", nil, a)
	if b, _ := os.ReadFile(filepath.Join(dir, "e2e", "smoke.e2e-spec.ts")); string(b) != "test('x', () => {});\n" {
		t.Error("file must be untouched outside the JS/TS + Playwright case")
	}
	if len(a.steps) != 0 {
		t.Errorf("no audit events expected, got %v", a.steps)
	}
}
