package pipeline

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/asqs/asqs-core/internal/testbootstrap"
)

// discardedSpecRepo is the Angular fixture's shape at the moment the survivor discard finishes:
// an ASQS-owned playwright.config.ts whose testMatch carries the `*.e2e-spec.*` pattern, the
// bootstrap smoke spec, and a repository `e2e/smoke.e2e-spec.ts` that the discard has just
// restored to its pre-run content — a bare `test(` with no @playwright/test import.
func discardedSpecRepo(t *testing.T) string {
	t.Helper()
	repo := t.TempDir()
	write := func(rel, body string) {
		t.Helper()
		full := filepath.Join(repo, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("package.json", `{"name":"a","scripts":{"start":"ng serve"},"dependencies":{"@angular/core":"^19.2.0"}}`)
	write("e2e/smoke.spec.ts", "import { test, expect } from '@playwright/test';\ntest('smoke', () => { expect(true).toBeTruthy(); });\n")
	// Restored by the discard: no import, exactly as the repository had it.
	write("e2e/smoke.e2e-spec.ts", "test('fixture', async ({ page }) => {\n  await page.goto('/');\n});\n")
	// The config as generation left it: the suffix pattern is present because the spec DID import
	// @playwright/test before the discard restored it.
	write("playwright.config.ts", "// Generated by ASQS e2e_framework_bootstrap — safe to edit or delete.\n"+
		"import { defineConfig, devices } from '@playwright/test';\n\nexport default defineConfig({\n"+
		"  testDir: './e2e',\n  testMatch: ['**/*.@(spec|test).?(c|m)[jt]s?(x)', '**/*.e2e-spec.?(c|m)[jt]s'],\n"+
		"  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],\n});\n")
	return repo
}

func configBody(t *testing.T, repo string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(repo, "playwright.config.ts"))
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// Run api-97ae558d51c11770e1fb82310419f5d8. The survivor discard removed the generated route specs
// and restored `e2e/smoke.e2e-spec.ts` to the fixture's import-less body, but playwright.config.ts
// still carried the `*.e2e-spec.*` pattern that only existed because that file HAD the import. The
// final verification loaded it and died with "ReferenceError: test is not defined", so a tree whose
// compile, unit tests and remaining smoke spec were all green shipped nothing.
func TestRefreshPlaywrightConfigAfterDiscard_dropsThePatternTheRestoredSpecNoLongerEarns(t *testing.T) {
	repo := discardedSpecRepo(t)
	aud := &capturingAuditor{}

	refreshPlaywrightConfigAfterDiscard(context.Background(), repo, "typescript", "playwright", aud)

	got := configBody(t, repo)
	if strings.Contains(got, "e2e-spec") {
		t.Errorf("the restored spec imports nothing, so its pattern must go:\n%s", got)
	}
	if !strings.Contains(got, "testDir: './e2e'") {
		t.Errorf("the rest of the config must survive:\n%s", got)
	}
	if !aud.has("pipeline.post_discard_playwright_config_refresh") {
		t.Errorf("the refresh must be audited: %v", aud.steps)
	}
}

// The discard must not edit the files it just restored: adding the import back would undo it.
func TestRefreshPlaywrightConfigAfterDiscard_neverRewritesTheRestoredSpec(t *testing.T) {
	repo := discardedSpecRepo(t)
	before, err := os.ReadFile(filepath.Join(repo, "e2e/smoke.e2e-spec.ts"))
	if err != nil {
		t.Fatal(err)
	}

	refreshPlaywrightConfigAfterDiscard(context.Background(), repo, "typescript", "playwright", &capturingAuditor{})

	after, _ := os.ReadFile(filepath.Join(repo, "e2e/smoke.e2e-spec.ts"))
	if string(before) != string(after) {
		t.Errorf("the restored spec was modified:\n%s", after)
	}
}

// A repository's own config is not ASQS-owned and is never touched; neither is a non-Playwright or
// non-JS run.
func TestRefreshPlaywrightConfigAfterDiscard_leavesForeignAndNonPlaywrightAlone(t *testing.T) {
	t.Run("repository-owned config", func(t *testing.T) {
		repo := discardedSpecRepo(t)
		own := "import { defineConfig } from '@playwright/test';\nexport default defineConfig({ testDir: './e2e', testMatch: ['**/*.e2e-spec.ts'] });\n"
		if err := os.WriteFile(filepath.Join(repo, "playwright.config.ts"), []byte(own), 0o644); err != nil {
			t.Fatal(err)
		}
		refreshPlaywrightConfigAfterDiscard(context.Background(), repo, "typescript", "playwright", &capturingAuditor{})
		if configBody(t, repo) != own {
			t.Errorf("a repository's own config must not be rewritten:\n%s", configBody(t, repo))
		}
	})
	for name, tc := range map[string]struct{ lang, framework string }{
		"java run":    {"java", "playwright-java"},
		"cypress run": {"typescript", "cypress"},
	} {
		t.Run(name, func(t *testing.T) {
			repo := discardedSpecRepo(t)
			before := configBody(t, repo)
			refreshPlaywrightConfigAfterDiscard(context.Background(), repo, tc.lang, tc.framework, &capturingAuditor{})
			if configBody(t, repo) != before {
				t.Errorf("%s must not touch the Playwright config", name)
			}
		})
	}
}

// A spec that still imports @playwright/test keeps the pattern: the refresh reflects disk, it does
// not simply strip.
func TestRefreshPlaywrightConfigAfterDiscard_keepsThePatternWhenASurvivorStillImports(t *testing.T) {
	repo := discardedSpecRepo(t)
	if err := os.WriteFile(filepath.Join(repo, "e2e/smoke.e2e-spec.ts"),
		[]byte("import { test, expect } from '@playwright/test';\ntest('kept', () => { expect(1).toBe(1); });\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	refreshPlaywrightConfigAfterDiscard(context.Background(), repo, "typescript", "playwright", &capturingAuditor{})

	if !strings.Contains(configBody(t, repo), "e2e-spec") {
		t.Errorf("a surviving spec that imports the API keeps its pattern:\n%s", configBody(t, repo))
	}
}

// Guards the assumption the fix rests on: the pattern is earned by the import, so removing the
// import removes the pattern on the next render.
func TestExtraPlaywrightTestMatch_isEarnedByTheImport(t *testing.T) {
	repo := discardedSpecRepo(t)
	rel, err := testbootstrap.RefreshPlaywrightConfig(repo, "typescript")
	if err != nil {
		t.Fatal(err)
	}
	if rel == "" {
		t.Fatal("the ASQS-owned config must be re-rendered")
	}
}
