package config

import (
	"context"
	"fmt"
	"strings"

	"github.com/asqs/asqs-core/internal/vcs"
	"github.com/asqs/asqs-core/internal/vcs/azuredevops"
	"github.com/asqs/asqs-core/internal/vcs/github"
)

// ShipEnsureOpenPullRequest lists open PRs/MRs for the ship branch or creates one after git push.
// httpsRemoteURL should be the origin HTTPS URL when known (e.g. workflow clone URL or Repo.RemoteURL("origin"))
// so Azure DevOps REST and Git auth stay aligned with the same org/project/repo even if vcs.provider is not azure_devops.
func (c *Config) ShipEnsureOpenPullRequest(ctx context.Context, httpsRemoteURL, owner, repo string, shipBranch, shipBase string) (prURL string, ok bool, err error) {
	ship := c.ActiveShip()
	title := "QualityBot: generated tests and docs"
	body := "Automated run: tests and documentation generated by QualityBot."

	if cl := c.azureRESTClientForHTTPSRemote(httpsRemoteURL); cl != nil {
		prs, err := cl.ListActivePullRequestsBySourceBranch(ctx, shipBranch)
		if err != nil {
			return "", false, err
		}
		if len(prs) > 0 {
			u := prs[0].WebURL
			if u == "" {
				u = fmt.Sprintf("ADO PR %d", prs[0].PullRequestID)
			}
			return u, true, nil
		}
		pr, err := cl.CreatePullRequest(ctx, title, body, shipBranch, shipBase)
		if err != nil {
			return "", false, err
		}
		u := pr.WebURL
		if u == "" {
			u = fmt.Sprintf("ADO PR %d", pr.PullRequestID)
		}
		_ = ship.DraftPR // Azure create payload could add isDraft in a follow-up
		return u, true, nil
	}

	switch normalizeVCSProvider(c.VCS.Provider) {
	case vcs.ProviderGitLab:
		cl := c.GitLabClient()
		if cl == nil {
			return "", false, fmt.Errorf("gitlab client not configured")
		}
		mrs, err := cl.ListOpenMergeRequestsBySourceBranch(ctx, owner, repo, shipBranch)
		if err != nil {
			return "", false, err
		}
		if len(mrs) > 0 {
			return mrs[0].WebURL, true, nil
		}
		mr, err := cl.CreateMergeRequest(ctx, owner, repo, shipBranch, shipBase, title, body)
		if err != nil {
			return "", false, err
		}
		return mr.WebURL, true, nil

	case vcs.ProviderBitbucket:
		cl := c.BitbucketClient()
		if cl == nil {
			return "", false, fmt.Errorf("bitbucket client not configured")
		}
		prs, err := cl.ListOpenPullRequestsBySourceBranch(ctx, owner, repo, shipBranch)
		if err != nil {
			return "", false, err
		}
		if len(prs) > 0 && prs[0].Links.HTML.Href != "" {
			return prs[0].Links.HTML.Href, true, nil
		}
		pr, err := cl.CreatePullRequest(ctx, owner, repo, title, body, shipBranch, shipBase)
		if err != nil {
			return "", false, err
		}
		if pr.Links.HTML.Href != "" {
			return pr.Links.HTML.Href, true, nil
		}
		return fmt.Sprintf("bitbucket PR #%d", pr.ID), true, nil

	case vcs.ProviderAzureDevOps:
		return "", false, fmt.Errorf("azure devops: set ASQS_AZURE_DEVOPS_TOKEN (or vcs.azure_devops.token) and use an Azure Repos HTTPS URL as the project clone URL for ship")

	default:
		gh := c.GitHubClient()
		if gh == nil {
			return "", false, fmt.Errorf("github client not configured")
		}
		headRef := owner + ":" + shipBranch
		prs, err := gh.ListPullRequestsByHead(ctx, owner, repo, headRef)
		if err != nil {
			return "", false, err
		}
		if len(prs) > 0 {
			return prs[0].HTMLURL, true, nil
		}
		pr, err := gh.CreatePullRequest(ctx, github.CreatePullRequestOptions{
			Owner: owner,
			Repo:  repo,
			Title: title,
			Body:  body,
			Head:  shipBranch,
			Base:  shipBase,
			Draft: ship.DraftPR,
		})
		if err != nil {
			return "", false, err
		}
		return pr.HTMLURL, true, nil
	}
}

// AzureDevOpsRESTClientForShipRemote returns an Azure DevOps Git REST client when the origin remote is Azure Repos
// (HTTPS org/project/_git/repo or SSH v3 URL) and a PAT is available, or when vcs.provider is azure_devops (configured client).
func (c *Config) AzureDevOpsRESTClientForShipRemote(remoteURL string) *azuredevops.Client {
	return c.azureRESTClientForHTTPSRemote(remoteURL)
}

// azureRESTClientForHTTPSRemote builds a Git REST client from an Azure DevOps HTTPS or SSH clone URL,
// or falls back to the configured Azure DevOps client when vcs.provider is azure_devops.
func (c *Config) azureRESTClientForHTTPSRemote(httpsRemoteURL string) *azuredevops.Client {
	if c == nil {
		return nil
	}
	u := strings.TrimSpace(httpsRemoteURL)
	lu := strings.ToLower(u)
	isAzureRemote := CloneURLIsAzureDevOpsHTTPS(u) ||
		strings.Contains(lu, "ssh.dev.azure.com") ||
		strings.Contains(lu, "vs-ssh.visualstudio.com")
	pat := c.CloneAuthTokenForURL(u)
	if isAzureRemote && pat != "" {
		org, project, rep, err := azuredevops.ParseRepoFromRemote(u)
		if err == nil {
			baseURL := strings.TrimSpace(c.VCS.AzureDevOps.BaseURL)
			return azuredevops.NewClient(pat, baseURL, org, project, rep)
		}
	}
	if normalizeVCSProvider(c.VCS.Provider) == vcs.ProviderAzureDevOps {
		return c.AzureDevOpsClient()
	}
	return nil
}

// DefaultRepoID returns owner/repo for metadata when no URL path is available (scheduler, serve).
func (c *Config) DefaultRepoID() string {
	o, r := c.ActiveDefaultOwnerRepo()
	if o == "" || r == "" {
		return ""
	}
	if normalizeVCSProvider(c.VCS.Provider) == vcs.ProviderAzureDevOps && strings.TrimSpace(c.VCS.AzureDevOps.Project) != "" {
		return fmt.Sprintf("%s/%s/%s", o, strings.TrimSpace(c.VCS.AzureDevOps.Project), r)
	}
	return o + "/" + r
}
